Fix ECKIT-166 and ECKIT-221 regression tests on cray

diff --git a/regressions/ECKIT-221.sh.in b/regressions/ECKIT-221.sh.in
--- a/regressions/ECKIT-221.sh.in
+++ b/regressions/ECKIT-221.sh.in
@@ -30,7 +30,27 @@ if [ "@ECKIT_HAVE_MPI@" == "1" ] && [ "@MPIEXEC@" != "MPIEXEC-NOTFOUND" ]; then
 
   create_file
 
-  @MPIEXEC@ -np 4 $exe "$fname"
+  @MPIEXEC@ @MPIEXEC_NUMPROC_FLAG@ 4 $exe "$fname"
+
+  set +e
+  filed_found=0
+  for i in $(awk 'BEGIN {for(i=0;i<40;i++) print i}'); do
+    ls -l $fname.0 $fname.1 $fname.2 $fname.3;
+    status=$?
+    if [ "$status" -eq 0 ]; then
+      files_found=1
+      break
+    else
+      sleep 5
+    fi
+    echo "Files not yet found or not yet accessible. Retry ($i)"
+  done
+  set -e
+
+  if [ "${files_found}" -eq 0 ]; then
+    echo "Files not found or not accessible"
+    exit 1
+  fi
 
   for i in 0 1 2 3; do
     cmp "$fname" "$fname.$i"
